ProOptions =
{
	bgStartFrame = { 120, 243, 268 },
	bgEndFrame   = { 180, 267, 291 },

	fontBigSize = 26, -- CHG: PrimeviL 
	--sliderWidth = 340,
	descColor	= R3D.RGB( 255, 255, 255 ), -- CHG: PrimeviL 
	disabledColor = R3D.RGBA( 125, 125, 125, 255 ),

	backAction = "PainMenu:AdjustFov(); PainMenu:ActivateScreen(MainMenu)",
	applyAction = "PainMenu:weaponsicons(); PainMenu:ApplySettings(true); Hud.CrossScale = Cfg.PROD_CrosshairSize; PMENU.SetItemVisibility('ApplyButton',false)",

	items =
	{
		GeneralTab =
		{
			type = MenuItemTypes.TabGroup,
			x = 122,
			y = 70,
			width = 776,
			height = 370,
			visible = true,
			align = MenuAlign.Left,
			
			items =
			{
				showfps =
				{
					type = MenuItemTypes.Checkbox,
					text = "Fps",
					desc = "Show the framerate (frame per second)",
					option = "PROD_ShowFPS",
					valueOn = true,
					valueOff = false,
					x	 = 140,
					y	 = 132,
					action = "",
					align = MenuAlign.None,
					applyRequired = true,
				},
				showping =
				{
					type = MenuItemTypes.Checkbox,
					text = "Ping",
					desc = "Show the ping",
					option = "PROD_ShowPing",
					valueOn = true,
					valueOff = false,
					x	 = 140,
					y	 = 172,
					action = "",
					align = MenuAlign.None,
					applyRequired = true,
				},
				showtimer =
				{
					type = MenuItemTypes.Checkbox,
					text = "Timer",
					desc = "Show the timer",
					option = "ShowTimer",
					valueOn = true,
					valueOff = false,
					x	 = 140,
					y	 = 212,
					action = "",
					align = MenuAlign.None,
					applyRequired = true,
				},
				timercountup =
				{
					type = MenuItemTypes.Checkbox,
					text = "Timer count up",
					desc = "Show the timer with count up",
					option = "ShowTimerCountUp",
					valueOn = true,
					valueOff = false,
					x	 = 140,
					y	 = 252,
					action = "",
					align = MenuAlign.None,
					applyRequired = true,
				},	
				currentweapon =
				{
					type = MenuItemTypes.Checkbox,
					text = "Current weapon",
					desc = "Show a current weapon icon",
					option = "PROD_CurrentWeapon",
					valueOn = true,
					valueOff = false,
					x	 = 140,
					y	 = 292,
					action = "",
					align = MenuAlign.None,
					applyRequired = true,
				},
				simpleicons =
				{
					type = MenuItemTypes.Checkbox,
					text = "Simple pro HUD",
					desc = "Show a simple HUD gfx",
					option = "PROD_SimpleIcons",
					valueOn = true,
					valueOff = false,
					x	 = 140,
					y	 = 332,
					action = "",
					align = MenuAlign.None,
					applyRequired = true,
				},
				coloreditems =
				{
					type = MenuItemTypes.Checkbox,
					text = "Brightskins ammo",
					desc = "Show brightskins for ammopak",
					option = "PROD_Colored_Items",
					valueOn = true,
					valueOff = false,
					x	 = 140,
					y	 = 372,
					action = "PainMenu:ApplySettings(true); PainMenu:coloreditems()",
					align = MenuAlign.None,
					applyRequired = false,
				},
				LowAmmoBorder =
				{
					type = MenuItemTypes.Border,
					x = 122,
					y = 450,
					width = 776,
					height = 180,
				},
				lowammo =
				{
					type = MenuItemTypes.StaticText,
					text = "LowAmmo:",
					x	 = -1,
					y	 = 472,
					action = "",
					--align = MenuAlign.None,
					--align = MenuAlign.Center,
					applyRequired = true,
				},
				lowammosnd =
				{
					type = MenuItemTypes.Checkbox,
					text = "Sound",
					desc = "Play LowAmmo Sound",
					option = "PROD_LA_Sound",
					valueOn = true,
					valueOff = false,
					x	 = 140,
					y	 = 500,
					action = "",
					align = MenuAlign.None,
					applyRequired = true,
				},
				lowammomsg =
				{
					type = MenuItemTypes.Checkbox,
					text = "Message",
					desc = "Show LowAmmo Message",
					option = "PROD_LA_Msg",
					valueOn = true,
					valueOff = false,
					x	 = 140,
					y	 = 540,
					action = "PainMenu:ApplySettings(); PainMenu:ActivateScreen(ProOptions); EnableLowAmmoOptions();",
					align = MenuAlign.None,
					applyRequired = false,
				},
				lowammomsgonchange =
				{
					type = MenuItemTypes.Checkbox,
					text = "Message Switch Weapon",
					desc = "Message Switch Weapon",
					option = "PROD_LA_Msg_Switch",
					valueOn = true,
					valueOff = false,
					x	 = -1,
					y	 = 500,
					action = "",
					align = MenuAlign.Right,
					applyRequired = true,
				},
				lowammomsgontake =
				{
					type = MenuItemTypes.Checkbox,
					text = "Message Pickup Weapon",
					desc = "Message Pickup Weapon",
					option = "PROD_LA_Msg_Pickup",
					valueOn = true,
					valueOff = false,
					x	 = -1,
					y	 = 540,
					action = "",
					align = MenuAlign.Right,
					applyRequired = true,
				},
				lowammodurationmsg =
				{
					type = MenuItemTypes.TextButtonEx,
					text = "Message Time",
					desc = "Message Time",
					option = "PROD_LA_Msg_Time",
					values = { 1, 2, 3 },
					visible = { 1, 2, 3 },
					x	 = 150,
					y	 = 590,
					action = "",
					align = MenuAlign.None,
					applyRequired = true,
				},
				speedmeter =
				{
					type = MenuItemTypes.TextButtonEx,
					text = "Speedmeter",
					desc = "Show the player's speed in game",
					option = "PROD_ShowSpeedmeter",
					values = { 0, 1, 2 },
					visible = { "None", "Classic", "Bar" },
					x	 = -1,
					y	 = 147,
					action = "",
					align = MenuAlign.Right,
					applyRequired = true,
				},
				HUDSize =
				{
					type = MenuItemTypes.TextButtonEx,
					text = TXT.Menu.HUDSize,
					desc = TXT.MenuDesc.HUDSize,
					option = "PROD_HUDSize",
					values = { 0.8, 1.0 },
					visible = { TXT.Menu.Small, TXT.Menu.Normal },
					x	 = -1,
					y	 = 187,
					action = "",
					align = MenuAlign.Right,
					applyRequired = true,
				},
				timersize =
				{
					type = MenuItemTypes.TextButtonEx,
					text = "Timer size",
					desc = "Set the timer size",
					option = "PROD_HUD_Fontsize_2",
					values = { 0, 1, 2 },
					visible = { "Small", "Normal", "Large" },
					x	 = -1,
					y	 = 227,
					action = "",
					align = MenuAlign.Right,
					applyRequired = true,
				},
				scoresize =
				{
					type = MenuItemTypes.TextButtonEx,
					text = "Score Size",
					desc = "Score Size",
					option = "PROD_Score_Size",
					values = { 0.8, 1.0 },
					visible = { TXT.Menu.Small, TXT.Menu.Normal },
					x	 = -1,
					y	 = 267,
					action = "",
					align = MenuAlign.Right,
					applyRequired = true,
				},
				--[[infosposix =
				{
					type = MenuItemTypes.TextButtonEx,
					text = "Infos position",
					desc = "Set the infos position",
					option = "PROD_Infos_Posx",
					values = { 0, 1 },
					visible = { "Right", "Left" },
					x	 = -1,
					y	 = 267,
					action = "",
					align = MenuAlign.Right,
					applyRequired = true,
				},]]--
				fpssize =
				{
					type = MenuItemTypes.TextButtonEx,
					text = "Infos size",
					desc = "Set the infos size (fps/ping/pl/ups)",
					option = "PROD_HUD_Fontsize_1",
					values = { 0, 1 },
					visible = { "Small", "Normal" },
					x	 = -1,
					y	 = 307,
					action = "",
					align = MenuAlign.Right,
					applyRequired = true,
				},
				ammolistposix =
				{
					type = MenuItemTypes.TextButtonEx,
					text = "Ammolist",
					desc = "Set the HUD ammolist",
					option = "PROD_AmmoList_Posix",
					values = { 0, 1, 2 },
					visible = { "None", "Right", "Left" },
					x	 = -1,
					y	 = 347,
					action = "",
					align = MenuAlign.Right,
					applyRequired = true,
				},
				weaponsicons =
				{
					type = MenuItemTypes.TextButtonEx,
					text = "Weapons icons",
					desc = "Set the icon above the weapons",
					option = "PROD_Weapons_Icons",
					values = { 0, 1, 2 },
					visible = { "None", "Classic", "Simple" },
					x	 = -1,
					y	 = 387,
					action = "",
					align = MenuAlign.Right,
					applyRequired = true,
				},
				zoomfx =
				{
					type = MenuItemTypes.TextButtonEx,
					text = "Zoom fx",
					desc = "Set the Zoom fx",
					option = "PROD_Zoom_FX",
					values = { 0, 1 },
					visible = { "None", "Classic" },
					x	 = -1,
					y	 = 4427,
					action = "",
					align = MenuAlign.Right,
					applyRequired = true,
				},	
			},
		},
		
		AdvancedTab =
		{
			type = MenuItemTypes.TabGroup,
			x = 122,
			y = 70,
			width = 776,
			height = 370,
			visible = false,
			align = MenuAlign.Right,

			items = 
			{
				killsound =
				{
					type = MenuItemTypes.Checkbox,
					text = "KillSound",
					desc = "KillSound",
					option = "PROD_KillSound",
					valueOn = true,
					valueOff = false,
					x	 = 140,
					y	 = 132,
					action = "",
					align = MenuAlign.None,
					applyRequired = true,
				},
				hitsound =
				{
					type = MenuItemTypes.Checkbox,
					text = "HitSound",
					desc = "HitSound",
					option = "PROD_HitSound",
					valueOn = true,
					valueOff = false,
					x	 = 140,
					y	 = 172,
					action = "",
					align = MenuAlign.None,
					applyRequired = true,
				},
				fragmessage =
				{
					type = MenuItemTypes.Checkbox,
					text = "FragMessage",
					desc = "FragMessage",
					option = "PROD_FragMessage",
					valueOn = true,
					valueOff = false,
					x	 = 140,
					y	 = 212,
					action = "",
					align = MenuAlign.None,
					applyRequired = true,
				},
				showscore =
				{
					type = MenuItemTypes.Checkbox,
					text = "Score",
					desc = "Show Score",
					option = "PROD_Score",
					valueOn = true,
					valueOff = false,
					x	 = -1,
					y	 = 132,
					action = "",
					align = MenuAlign.Right,
					applyRequired = true,
				},	
				teammateicon =
				{
					type = MenuItemTypes.Checkbox,
					text = "Teammate's icon",
					desc = "Show a icon above the teammate's head",
					option = "PROD_Teammate_Icon",
					valueOn = true,
					valueOff = false,
					x	 = -1,
					y	 = 172,
					action = "",
					align = MenuAlign.Right,
					applyRequired = true,
				},
				thinshaft =
				{
					type = MenuItemTypes.Checkbox,
					text = "Thin shaft",
					desc = "Show a Thin shaft fx",
					option = "PROD_ThinShaft",
					valueOn = true,
					valueOff = false,
					x	 = -1,
					y	 = 212,
					action = "",
					align = MenuAlign.Right,
					applyRequired = true,
				},				
				fov =
				{
					type = MenuItemTypes.Slider,
					text = "Fov",
					desc = "Set the field of view",
					option = "FOV",
					minValue = 95,
					maxValue = 150,
					x	 = 150,
					y	 = 272,
					action = "",
					applyRequired = true,
				},
				zoomfov =
				{
					type = MenuItemTypes.Slider,
					text = "Zoom Fov",
					desc = "Set the fiel d of view for zoom",
					option = "ZoomFOV",
					minValue = 0,
					maxValue = 95,
					x	 = 150,
					y	 = 312,
					action = "",
					applyRequired = true,
				},		
				maxfps =
				{
					type = MenuItemTypes.Slider,
					text = "Max Fps",
					desc = "Set the maximum framerate in game",
					option = "MaxFpsMP",
					minValue = 0,
					maxValue = 125,
					x	 = 150,
					y	 = 352,
					action = "",
					applyRequired = true,
				},
				crosshairsize =
				{
					type = MenuItemTypes.Slider,
					text = "Crosshair size",
					desc = "Set the crosshair size",
					option = "PROD_CrosshairSize",
					minValue = 0,
					maxValue = 2,
					isFloat = true,
					x	 = 150,
					y	 = 392,
					action = "",
					applyRequired = true,
				},
			},
		},

		GeneralSettings =
		{
			text = TXT.Menu.General,
			desc = TXT.MenuDesc.General,
			x	 = 212,
			y	 = 96,
			align = MenuAlign.Center,
			action = "PainMenu:HideTabGroup(PainMenu.currScreen.items.AdvancedTab, 'AdvancedTab'); PainMenu:ShowTabGroup(PainMenu.currScreen.items.GeneralTab, 'GeneralTab')",
			sndAccept   = "menu/magicboard/card-take",
			fontBigSize = 26,
		},
		
		AdvancedSettings =
		{
			text = TXT.Menu.Advanced,
			desc = TXT.MenuDesc.Advanced,
			x	 = 392,
			y	 = 96,
			align = MenuAlign.Center,
			action = "PainMenu:HideTabGroup(PainMenu.currScreen.items.GeneralTab, 'GeneralTab'); PainMenu:ShowTabGroup(PainMenu.currScreen.items.AdvancedTab, 'AdvancedTab')",
			sndAccept   = "menu/magicboard/card-take",
			fontBigSize = 26,
		},
		EmptyBorder =
		{
			type = MenuItemTypes.Border,
			x = 122,
			y = 117,
			width = 776,
			height = 322,
		},
		StaticWeaponSettingsBorder =
		{
			type = MenuItemTypes.Border,
			x = 478,
			y = 80,
			width = 255,
			height = 44,
		},
		StaticWeaponSettings =
		{
			text = "Weapon View",
			desc = "Static Weapon Settings",
			x	 = 605,
			y	 = 96,
			align = MenuAlign.Center,
			action = "FirstWeaponsOption(); PainMenu:ActivateScreen(StaticWeaponSettings); EnablePositionOptions(); EnableCustomOptions()",
			sndAccept   = "menu/magicboard/card-take",
			fontBigSize = 26,
		},
	}
}
